---
title: "Lab 9: Correlation and Introduction to Simple Linear Regression"
author: "NAME"
format: html
embed-resources: true
html-math-method: mathml
  warning: false
  echo: true
  error: false
---

## Before you start:

1. Complete the Lab Primer linked in Canvas.  
2. Be sure you have opened the `lab9-intro-two-quant-student.Rproj` file.  
3. Change the name of the **QMD** file only to your last name, first initial, e.g., `OtterM-lab9-intro-two-quant-student.qmd`. You will have to close the QMD document to rename the file. 
4. Change the "NAME" above after `author:` to your name, leaving it in quotes: "Monte Otter" 

## Skills
* Given a study, distinguish between explanatory and response variables
* Given a set of raw data, make a scatterplot or regression output using R
* Given a set of raw data, be able to calculate correlation
* Be able to use correlation to identify the strength and direction of a linear association
* Given a scatterplot, identify patterns such as positive and negative associations
* Given standard regression output, identify and utilize key parts of the output (estimated slope, intercept)

These skills incorporate LTs 17 and R LTs R8, R9, and R10.


*Tip: putting two spaces after a line forces the next line in your Quarto document to also be a new line in your knitted document.*

*Tip: equations in will ignore any attempt to include spaces, unless you insert a `~` inside the equation where you want the space.* For example, in our BAC-Beers problem from class (hover your mouse over each formula to see what it would knit like): $x_{number of beers}$ versus $x_{number~of~beers}$

*Tip: If you want to test out two lines of code, such as for a plot (such as you've seen previously with piped functions), you have to run them **together**, not one at a time.*

Here are some symbols that you might find useful: 

$\hat{y}$

$\hat{y}_{word}$  

$x_{word}$  

$\beta_{word}$  


**Reminder:** Before starting this lab, let us load the `ggformula` and `mosaic` packages we need for statistical and graphical functions using the `library()` function.

```{r}
#| label: setup
#| include: false
library(tidyverse)


```

## Scenario 1: Palmer Penguins

As part of the Palmer Station Long Term Ecological Research Program in Antarctica, Kristen Gorman has been collecting size measurements for adult foraging Adelie, Chinstrap, and Gentoo penguins observed on islands in the Palmer Archipelago near Palmer Station, Antarctica. The measurements include penguin species, size (flipper length, body mass, bill dimensions), and sex. Penguins were measured after a random number of other penguins were passed. Let's now investigate if a linear model with flipper length can explain any differences in body mass. The data are in `penguins.csv`.

### 1.1.

Name the response and explanatory variables of interest and, for each, state the type of variable (quantitative or qualitative).

> Response:

> Explanatory:

### 1.2.

What type of study is this (observational or experimental)? Justify your answer in the context of the study.

> Insert answer here  

### 1.3.

Exploratory Data Analysis: Insert a code chunk below to create an appropriate graphic and calculate any appropriate summary statistics. Modify the plot so that the x axis spans from 170 to 240, and so that the y axis spans from 2600 to 6400.

< Insert code chunk here >  

### 1.4.

What is the simplest form (linear, nonlinear, etc) of the relationship between the body mass of penguins in the Palmer archipelago and flipper length?

> Insert answer here  

### 1.5.

What is the strength and direction of the linear relationship? Cite your evidence. (You may want to refer to 1.3 / use your best evidence)

> Insert answer here  

### 1.6.

Create a scatterplot of the data, including both the axis modification and the estimated linear model on the plot.

< Insert code chunk here >  

### 1.7.

Create your linear model. Then, write the code below to print out the coefficients for your estimates of slope and intercept of your linear model between between the body mass and flipper length and write them below.

< Insert code chunk here >  

> $b_0$ = 

> $b_1$ = 

### 1.8.

Write the equation for your estimate of the linear model between body mass and flipper length. Use the appropriate formatting for symbols.

> Insert answer here  

### 1.9.

Interpret the slope of the linear model, in context.

> Insert answer here  

### 1.10.

First interpret the intercept of the linear model, in context (provide the mathematical interpretation, whether it makes sense or not practically). Then, explain whether this interpretation is practical.

> Insert answer here  

### 1.11.

What is the average body mass for Palmer penguins with a flipper length of 200 mm? Show your work in a code chunk and write the answer below.

< Insert code chunk here >  

> Insert answer here  

### 1.12.

One male Gentoo penguin on Biscoe island weighed 5400 g and had a flipper length of 213 mm in 2009. Calculate the residual for the data point. Show your work in the code chunk. What does that value mean for the body mass in context?

< Insert code chunk here >  

> Insert answer here  

### 1.13.

Does the linear model with flipper length explain much of the variability in body mass of penguins in the Palmer Archipelago? How much variability does it explain? Does that seem like a good model to use for predictions (evaluate the strength of the model fit)?   

< Insert code chunk here >  

> Insert answer here 



## Scenario 2: Primate Brain Size   

Human brains have a large frontal cortex with excessive metabolic demands compared with the brains of other primates. However, the human brain is also three or more times the size of the brains of other primates. Is it possible that the metabolic demands of the human frontal cortex are just an expected consequence of greater brain size? Sherwood et al. (2006) investigated this question. Let's first look at the relationship of glia-neuron ratio (an indirect measure of the metabolic requirements of brain neurons) and the brain mass (grams) of *non-human* primates, to see if brain mass explains the glia-neuron ratio. The data set includes a random sample of one to two species from each Family of primates (which ensures the species sampled are considered independent). 
 The data are found in `primate-glia-neuron-ratio.csv`.

### 2.1.

Name the response and explanatory variables of interest and, for each, state the type of variable (quantitative or qualitative).

> Response:

> Explanatory:

### 2.2.

TRUE or FALSE? We could generalize the results of this study to all primates, including humans. Bold your answer.

TRUE or FALSE? We could determine causality from the results of this study. Bold your answer.

### 2.3.

Explanatory Data Analysis: Insert a code chunk below to create an appropriate graphic and calculate any appropriate summary statistics.

< Insert code chunk here >  

### 2.4.

What is the simplest form (linear, nonlinear, etc) of the relationship between glia-neuron ratio and brain mass?

> Insert answer here  

### 2.5.

Is it appropriate to interpret the calculated correlation coefficient or create a linear model for these data?

> Insert answer here  