---
title: "Lab 7: Paired T-test"
author: "NAME"
format: html
embed-resources: true
html-math-method: mathml
execute: 
  warning: false
  echo: true
  error: false
---

## Before you start:

1. Complete the Lab Primer linked in Canvas.  
2. Be sure you have opened the `lab7-paired-t-student.Rproj` file.  
3. Change the name of the **QMD** file only to your last name, first initial, e.g., `OtterM-lab7-paired-t-student.qmd`. You will have to close the QMD document to rename the file. 
4. Change the "NAME" above after `author:` to your name, leaving it in quotes: "Monte Otter" 


## Skills

- Given a dataset, be able to determine if the appropriate assumptions are met to conduct a parametric hypothesis test (LT 22)
- Identify a matched pairs design and what inference is appropriate in this situation  (LT 12)
- Conduct a statistical inference (confidence interval or hypothesis test) based on matched pairs data  (R4, R5)
- Identify and justify the scope of generalizability (LT 5)
- Write the parameter of interest and the hypotheses for a two-sample study (LT 21)
- Interpret a p-value and evaluate the strength of evidence in a hypothesis test in the context of the study (LT 14)
- Interpret a confidence interval in the context of the study (LT 8)
- Evaluate a confidence interval to make a claim about the population parameter in the context of the study (LT 9)
- Use the study design to determine if causality is appropriate (LT 13)
- Identify and describe Type I/Type II errors in the context of the study (LT 16)
- Identify and justify the study type (LT 11)
- Evaluate exploratory data analysis in support of a conclusion about a parameter(s) within the context of the study (LT 4)
- Justify when the results of an inference are trustworthy based on the conditions of the inferential analysis (LT 10)

Here are some symbols that you might find useful:  
$H_0$ $H_1$ $\sigma$ $\mu$ $\mu_0$ $\mu_{word}$ $\mu_{d~word}$ $\neq$

*Tip: putting two spaces after a line forces the next line in your Quarto document to also be a new line in your knitted document.*

*Tip: hover your mouse over a formula to see how it would look in the final document.*

**Reminder:** Before starting this lab, let us load the `tidyverse`,`ggformula`, and `mosaic` packages we need for statistical and graphical functions using the `library()` function.

```{r}
#| label: setup
#| include: false

```


### Part 1: Bear Weights

Katmai National Park is famous for the salmon run each summer and the brown bear feast that accompanies it. Brown bears can lose roughly 30% of their body weight while hibernating (spending the winter sleeping), so it is essential that they pack on the pounds during the summer. They feed on high-caloric foods, like sockeye salmon (one salmon can be ~4000 calories), but also on sedges (a grass, often eating about 30 lbs of sedges a day), berries, grubs, etc. Over the course of the summer, bears have to add hundreds of pounds to their body weight to make up for weight lost during the past hibernation, and to survive the next hibernation; at peak season, brown bears can add up to four pounds of weight per day! Over the summer, the brown bears can really pack it on! (case in point: see pictures of the [Katmai Fat Bear champion final contenders](https://explore.org/fat-bear-week)).

You are a researcher interested in the weight gain of brown bears over the summer. You want to know if the Katmai bears, with an unusually large salmon run to feast on this year, gained more than 30% of their autumn-body weight over the summer, or roughly 345 lbs. You weigh a random selection of brown bears in Katmai NP at the beginning of June, and then weigh the same bears at the end of September and record their weight (in pounds). The data are in `fat-bear-weights.csv`, in the vectors `sept_lb` and `june_lb`. 


## 1.1.

State the parameter of interest.  

> Insert answer here    


## 1.2.

State your null and alternative hypotheses, both symbolically and verbally. Indicate the difference equation you are going to use prior to your hypotheses.  
 
> Insert answer here     
   

## 1.3.

What type of study design (two independent samples or matched pairs) is appropriate for this analysis? Justify your response.

> Insert answer here   


## 1.4.

Assess the conditions needed to conduct statistical inference (normality and sufficient sample size). Include any code needed to assess this problem. 

< Insert code chunk here >  

> Insert answer here  


## 1.5.

Calculate the appropriate test statistic and p-value 'by hand' (i.e., using the numerical summary functions in R, without using the `t.test()` function); show your work. Provide the test statistic and p-value below.  

< Insert code chunk here >  

> t~statistic~ =   
> p-value =   


## 1.6.

Interpret your p-value in the context of the scenario.  

> Insert answer here  


## 1.7.

Write a strength of evidence statement for the p-value, using a significance level of 0.05.  

> Insert answer here  


## 1.8.

Calculate and interpret the 95% confidence interval (CI) for the mean difference of weight in Katmai bears over summer ‘by hand’ (i.e., using numerical summary functions in R, as well as one line of code to determine the critical value (denoted by t*)). 

< Insert code chunk here >   

> Insert answer here  


## 1.9.

Evaluate your confidence interval for evidence for the research question. Explain and justify your answer in the context of the study.

> Insert answer here  


## 1.10.

Could the researchers determine that the month *caused* any difference in bear weight? Justify your answer.

> Insert answer here  


## 1.11.

Given your evidence, what are the two possible decisions you could be making (correct, type I, type II)? After identifying them, interpret the error in the context of the problem (i.e., describe the definition of your chosen error, but with the context of the problem in place of words like "null hypothesis").

> Insert answer here  


### Part 2: Electric Eel Species  


Neotropical rivers support a diverse array of endemic taxa, including electric fishes in the Gymotiformes family. A comprehensive survey of the main channels of the Amazon River and its major tributaries (smaller rivers that flow into the Amazon River) found 43 electric fish species occur. How those species are distributed within the river is an important ecological question. Researchers studying the number of electric fish species living in various parts of the Amazon basin were interested in whether the presence of tributaries was related to higher local numbers of electric fish species below tributary junctions in the main rivers. ("Local diversity" is defined as the diversity in that specific location, rather than the diversity regionally or across the entire river system). They counted the number of electric fish species in the river above and below the entrance point of a major tributary at different randomly selected locations. *(Note, the water flows from upstream toward downstream, or from above the point a tributary enters to below that point).* Data are in `amazon-electric-eel-species.csv`. Define the difference as `Downstream` minus `Upstream`.   
*Based on Fernandes et al 2004, Science*


## 2.1.

State the null and alternative hypotheses, both symbolically and verbally.

> Insert answer here   
 

## 2.2.

What type of study design (two independent samples or matched pairs) is appropriate for this analysis? Justify your response.

> Insert answer here   


## 2.3.

What type of study was performed (observational, experimental)? Justify your response. 

> Insert answer here   


## 2.4.

Assess the conditions for conducting the appropriate inference analyses in the context of the problem (normality and sufficient sample size). Use the skills you learned in Lab 5 & 6 as needed to complete this question. You may need to run code to get some of the answers, but you must show the code and justification within this document.   

< Insert code chunk here >  

> Insert answer here   



## 2.5.

Perform an appropriate hypothesis test using the `t.test()` function, then provide your test statistic, degrees of freedom, and p-value. 

< Insert code chunk here > 

> Insert answer here  



## 2.6.

Interpret your p-value in the context of the scenario.

> Insert answer here  


## 2.7.

Evaluate the strength of your evidence from the hypothesis test, using a 0.01 significance level.  

> Insert answer here   


## 2.8.

Using the `t.test()` function, calculate the 99% confidence interval for the difference of the number of species from locations downstream and upstream of major tributaries.   

< Insert code chunk >  



## 2.9.

Provide a second piece of evidence from EDA (Exploratory Data Analysis) that supports the results of your inference to answer the research question if there are more species of electric fishes downstream of major tributaries in the Amazon than upstream.  

< Insert code chunk as needed here >

> Insert answer here  



## 2.10.

Could you generalize your conclusion to the population of interest?  If yes, explain why. If not, explain why and, if applicable, identify the population to which you can generalize.    

> Insert answer here   


## 2.11.

Can you trust the statistical methods used to calculate your inference results (p-value, confidence interval?) Justify your answer, including what the study has and why or why not that allows you to trust the results.  

> Insert answer here   


## 2.12.

First calculate the effect size for our hypothesis test (the Cohen's d). Then, state the value of this effect size and use the guidelines from your notebook to classify it as small, medium, or large.

< Insert code chunk here >  

> Insert answer here

## 2.13.

If a similar study $(n = 60)$ had obtained a p-value of 0.037 and a Cohen's d (effect size) of 0.25, which study would provide more evidence of a **meaningful** difference between the number of species downstream and upstream of major tributaries of the Amazon river?

> Insert answer here